### ISSUE TITLE
CPU Machine and Predictions of Unlabeled Data

### ISSUE THREAD

**Issue by Mahhos** [timoschick/pet#11]
Thanks for the great repo. I have got 2 questions. 

1. How many days you expect a customized task with sizes of the train: 610, dev: 500, test: 1000, unlabeled data: 2000 would take on a CPU machine? It's been four days and the code is still going :D  this is the current step `"learning_rate": 3.1000000000000004e-06, "loss": 0.007363705812799708, "step": 3450}`

2. To get the predictions/final_labels for unlabeled data which folder/file should we look at?
I have 7 folders in my output_directory so far. `p0-i0, p0-i1, p0-i2, p1-i0, p1-i0, p1-i1, p1-i2, final` I designed 2 patterns (0,1) for my customized_PVP.  
There are two files in my output_directory as well: `result_test.txt` and `unlabeled_logits.txt`.  The first three lines in my `unlabeled_logits.txt`:
 -1
8.052350375527427 5.843138097046414
14.612752109704642 2.8329479116033762

**Comment by timoschick** [comment]
Hi @Mahhos,

1. I have never tried using PET on CPU so I have no experience with regards to the expected training time, sorry. If you can somehow get access to a single GPU with >8GB of memory, you should be able to perform training for your data in less than a day.

2. Each folder `pX-iY` corresponds to the results obtained in the `Y`th iteration of training using pattern `X`. You'll probably only be interested in the results of the final, distilled model, which you will find in `final/p0-i0` once training is complete. Note that by default, the final model does not compute predictions for the unlabeled data, but only for the validation (or test) data. You can simply define your `get_dev_examples()` method to return the same data as your `get_unlabeled_examples()` method if you want the final model to annotate the unlabeled data.

**Comment by Mahhos** [comment]
Thank you so much.

**Comment by timoschick** [comment]
You're welcome!

**Comment by Mahhos** [comment]
Having `get_dev_examples()` method to return the same data as the `get_unlabeled_examples()` method
raised this error. It seems that it expects labels for `dev.csv`. However, the `unlabeled.csv` does not have labels and has `,` instead. 

`  File "/pet-master/pet/preprocessor.py", line 83, in get_input_features
    label = self.label_map[example.label] if example.label is not None else -100
KeyError: ','`

**Comment by timoschick** [comment]
Ahh right, the code expects labels for your development file in order to compute accuracy on the dev set. I don't know how your file `unlabeled.csv` and your corresponding `TaskProcessor` looks like, but you can bypass this by simply assigning some (random) label to all examples. For example, you can make a method `get_dev_examples()` similar to this:

    def get_dev_examples(self, data_dir) -> List[InputExample]:
        examples = self.get_unlabeled_examples(data_dir)
        for example in examples:
             example.label = self.get_labels()[0]
        return examples
