### ISSUE TITLE
Romanian language

### ISSUE THREAD

**Issue by grigo210** [timoschick/pet#16]
Hi!
This model can be used for romanian language?

**Comment by timoschick** [comment]
Hi @grigo210, PET is not a model, but a training method for pretrained language models. If you happen to find a pretrained LM in Romanian (a good starting point might be https://huggingface.co/models), you can of course train it using PET. You can find some results for PET with languages other than English here: https://arxiv.org/abs/2001.07676

**Comment by grigo210** [comment]
Thank you!
