### ISSUE TITLE
Imbalanced data

### ISSUE THREAD

**Issue by hubert98** [timoschick/pet#17]
I would like to use pet for imbalanced data (Class1 ~80% of data, Class 2-5 ~20% of data) 
Do you have experience with or training tips for using PET with imbalanced classes?

**Comment by timoschick** [comment]
Hi @hubert98, the only imbalanced dataset we've used PET for so far is [CommitmentBank](https://github.com/mcdm/CommitmentBank), which is part of SuperGLUE. For this dataset, we found that iterative PET (iPET) greatly improves performance - so if you have enough unlabeled data, this is something I would definitely recommend trying. In iPET, the distribution of classes for new training sets is adopted from the original training set's distribution. So if for some reason you happen to know that the class distribution of your training data is different from the (expected) distribution of your test data, you may need to change this manually. Apart from that, I don't have any tips for using PET with imbalanced classes as my experience with PET on such datasets is limited.

**Comment by hubert98** [comment]
Thank you very much for the feedback!
