### ISSUE TITLE
TensorFlow 2.4 support is not available

### ISSUE THREAD

**Issue by Rishabbh-Sahu** [timoschick/pet#22]
Hi Timo Schick,

Thanks for creating this repo. I've been looking to implement this using TensorFlow 2.4 and multi-gpu setup for dialog-nlu task. Are you planning to release Tensorflow 2.4 version for the same which can be converted to tflite to test in mobile devices.

Thanks.

**Comment by timoschick** [comment]
Currently I do not have plans to release a version of PET that is compatible with TensorFlow 2.4.
If you want to implement PET yourself in a way that is compatible with TensorFlow, let me know if you have any specific questions.

**Comment by Rishabbh-Sahu** [comment]
Thanks for the reply. Will surely get in touch with you.

**Comment by danielkorat** [comment]
Hi @Rishabbh-Sahu 
Did you implement/find a TensorFlow version?
Thanks :)
