### ISSUE TITLE
In what format should the csv files listed in the taskprocessor be?

### ISSUE THREAD

**Issue by BleepLogger** [timoschick/pet#31]
In what format should the csv files listed in the taskprocessor be?
What should the row names in the csv files be?
Examples of files like this?

**Comment by timoschick** [comment]
This strongly depends on the task you want to solve. For Yelp, Ag's News and Yahoo, the implemented task processors use [this format](https://drive.google.com/drive/u/0/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M). For SuperGLUE, they use the default SuperGLUE jsonl format. You can also look at [this example](https://github.com/timoschick/pet/blob/master/examples/custom_task_processor.py) to see how you can write your own custom task processors for arbitrary file formats.
