### ISSUE TITLE
GPT2 SEQUENCE_CLASSIFIER_WRAPPER missing

### ISSUE THREAD

**Issue by FlorisFok** [timoschick/pet#35]
gpt2 is missing the SEQUENCE_CLASSIFIER_WRAPPER; GPT2ForSequenceClassification, which is available in the transformer module.

**Comment by timoschick** [comment]
Hi Floris,

I don't know GPT2ForSequenceClassification well enough to be sure that it works with our codebase out of the box, which is why I didn't add it. If you've already added it yourself and didn't observe any problems, feel free to create a pull request :)
