### ISSUE TITLE
Typo in the EACL2021 paper

### ISSUE THREAD

**Issue by tomohideshibata** [timoschick/pet#37]
Thank you for releasing your codes.

I have found a small typo in your EACL2021 paper.

In the explanation for MNLI in Sec 4.1,  the followings should be opposite in the verbalizers examples.
- "Wrong" and "Right"
- "No" and "Yes"

![image](https://user-images.githubusercontent.com/16042472/121633717-48dd6d00-cabe-11eb-9d52-4ca09dd855b2.png)

Thanks.

**Comment by BleepLogger** [comment]
Hi, the formula, in case you didn't understand is
`v1 * (v2 ** (1/y_prediction)) / ((42x + v2/vx)/2y)`

**Comment by BleepLogger** [comment]
It took me quite a while to calculate it.

**Comment by BleepLogger** [comment]
> Hi, the formula, in case you didn't understand is
> `v1 * (v2 ** (1/y_prediction)) / ((42x + v2/vx)/2y)`

so following that, v is 0.5, which maps to 'maybe', and v1 and v2 respectively are 0 (no) and 1 (yes), so whatever is written there is correct.

**Comment by tomohideshibata** [comment]
Thank you for your response, but I haven't understood what you mean.

> v1 * (v2 ** (1/y_prediction)) / ((42x + v2/vx)/2y)
First, where can I find this formula?

**Comment by timoschick** [comment]
Hi @tomohideshibata, you are absolutely correct, that is indeed an error in the paper (that, for some reason, noone has spotted before). Thanks for pointing this out!
