### ISSUE TITLE
how to get the datafiles

### ISSUE THREAD

**Issue by jackfeinmann5** [timoschick/pet#44]
Hi
I am not sure how to download the data for each task, could you kindly upload the files somewhere or include the links from which repo you got the data for each tasks?

Could you also comment how I can get unlabeled.jsonl for each task like boolq or rte?

thanks for your help

**Comment by jackfeinmann5** [comment]
Hi
regarding this one, I downloaded RTE, the tasks.py require a "word" field, but there is no one in the original files, could you please assist me with this? thanks

**Comment by timoschick** [comment]
If you're interested in the SuperGLUE tasks, you can find all train/unlabeled examples in the [FewGlue repository](https://github.com/timoschick/fewglue); the original train/validation/test files are available [here](https://super.gluebenchmark.com/). Data for AG's News, Yelp Full and Yahoo Questions is from [here](https://drive.google.com/drive/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M). For all summarization tasks, required files are loaded using huggingface's datasets library.
