### ISSUE TITLE
How to assign GPU?

### ISSUE THREAD

**Issue by windhxs** [timoschick/pet#52]
It seems that your code will utilize all GPU，but I share a server with others, and it turns out to be something like `cuda out of memory`. Is there any parameters that can assign which GPU to use?

**Comment by stefan-it** [comment]
Hi @windhxs ,

fastest solution would be to set `CUDA_VISIBLE_DEVICES` environment variable (incl. the id of your desired GPU to use), such as: `export CUDA_VISIBLE_DEVICES=1` or you can prepend this variable when calling python: `CUDA_VISIBLE_DEVICES=1 python3 <script>.py`.

**Comment by windhxs** [comment]
thanks a lot!
