### ISSUE TITLE
why Copa batch size is 1

### ISSUE THREAD

**Issue by dorost1234** [timoschick/pet#56]
Hi
I am looking into the task helper for CoPA, and to me you could potentially do it batchwise, I was wondering if there was any reason to enforce batch size of 1 for multiple token verbalizers?

thanks for your help on this

**Comment by timoschick** [comment]
Hi @dorost1234, this only affects evaluation, training should work with larger batch sizes. While it would absolutely be possible to implement evaluation batchwise, the [current implementation of `_get_choice_log_probability`](https://github.com/timoschick/pet/blob/c33d2089f16d52483a4359ba6d6482b874e08853/pet/task_helpers.py#L335) requires a batch size of 1 as this makes the decoding strategy more straightforward to implement (we don't have to deal with different examples having a different number of mask tokens).
