### ISSUE TITLE
Multilabel support

### ISSUE THREAD

**Issue by LuketheDukeBates** [timoschick/pet#61]
Hello! Thanks for the great papers and repo. I'm curious if it is possible to do multilabel classification using PET? Looking through the code, it seems like it is not.

**Comment by timoschick** [comment]
Hi @abaheti95, this should be explained in the [README](https://github.com/timoschick/pet#readme). If you want to get the exact same results, you may need to use the [`v1.1.0` branch](https://github.com/timoschick/pet/tree/v1.1.0). Please create a separate issue if you have any further questions!
