### ISSUE TITLE
patterns for GLUE

### ISSUE THREAD

**Issue by dorost1234** [timoschick/pet#62]
Hi
I am looking for patterns for GLUE, I appreciate your response, do you know of any work which produced a good pattern for GLUE?
thank you very much

**Comment by timoschick** [comment]
Hi @dorost1234, I'm not aware of any work on patterns for GLUE - sorry! However, for NLI tasks you may look at the patterns that we've used for SuperGLUE, for SST you may try the pattern [that we've used for IMDb here](http://www.timoschick.com/research/2021/05/19/dino.html) and for STS, maybe something similar to [these formulations](https://arxiv.org/pdf/2104.07540.pdf) might help.

**Comment by dorost1234** [comment]
thanks
