### ISSUE TITLE
--train_examples

### ISSUE THREAD

**Issue by savasy** [timoschick/pet#65]
Dear Timo,
 Does the parameter "--train_examples" refer to training set size. So, I mean, setting it to 0 (zero) means zero-shot learning, doesn't it?
Thank you

**Comment by timoschick** [comment]
Hi @savasy, yes, `--train_examples` refers to the training set size. However, there seems to be an issue with `--train_examples 0` (which is interpreted as using *all* training examples). See [this issue](https://github.com/timoschick/pet/issues/66) for an explanation and workarounds. If you are not using iterative PET, you can also simply set the number of training steps to 0 for a zero-shot setting.

**Comment by savasy** [comment]
Thank you @timoschick ! It is very helpful!
