### ISSUE TITLE
GenPET commands with GPT-2

### ISSUE THREAD

**Issue by yonwu** [timoschick/pet#84]
Hi, @timoschick 

Thanks for the excellent work on the PET project.

I am trying the GenPET now and successfully trigger training with the PEGASUS model. 
I saw in the code in wrapper, there is some GPT-2 related code. 

If I would like to try GenPET with GPT-2, what would the command looks like, or is it enough that I only change the model to GPT2 instead of PEGASUS ?

Thanks for your answer in advance!

Best, 
Yongchao

**Comment by timoschick** [comment]
Hi @yonwu, using GenPET with GPT-2 currently is not supported: The GenPET code does some things that are specific to PEGASUS (or to encoder-decoder architectures in general). I currently don't have time to update the code myself to make it work with GPT-2, so if you want that, you probably have to make the necessary changes yourself 😞

**Comment by yonwu** [comment]
Hi, @timoschick 
Thanks for your answer! I close this issue then.
