### ISSUE TITLE
RuntimeError on eval method

### ISSUE THREAD

**Issue by xruifan** [timoschick/pet#86]
Hi, 

I tried to use my final classifier to predict the class of a new instance, using the method `eval` as described [here](https://github.com/timoschick/pet/issues/29#issuecomment-831265193). After I assigned the device 'cuda', I got an error saying `RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select`. 

Fan

**Comment by serfinxx** [comment]
Hi, after I changed the line [here](https://github.com/timoschick/pet/blob/21d32de975a911bfa0261827c9bd23dc4f0e4aa2/pet/wrapper.py#L366-L368) in `eval` method as following:
```
            batch = {k: t.to(device) for k, t in batch.items()}
            labels = batch['labels']
            indices = batch['idx']
```
to: 
```
            batch = {k: t for k, t in batch.items()}
            labels = batch['labels'].to(device)
            indices = batch['idx'].to(device)
```
the method allowed the test data to be assigned to device 'cuda' normally.

**Comment by timoschick** [comment]
Did you move the model to GPU (in the example you linked, that would be `model.model.to('cuda')`) before running the evaluation?

**Comment by xruifan** [comment]
No, I didn't. The code worked perfectly after I added the line, thank you so much!
