### ISSUE TITLE
Potential use with GPT-2?

### ISSUE THREAD

**Issue by fen0s** [timoschick/pet#9]
This thing looks amazing so far! Anyone tried using it for minimized costs GPT training? If yes, can anyone share examples of generated text, and preferably, how to do it?

**Comment by timoschick** [comment]
Hi @fen0s, thanks for your kind words :) 
We are currently investigating if and how PET can be used in combination with generative models like GPT-2. We'll update this repo once our experiments are finished, but this is probably going to take a while.
